affinityCookieTtlSec: 0
backends:
- balancingMode: UTILIZATION
  capacityScaler: 1.0
  group: https://www.googleapis.com/compute/v1/projects/mensal2/regions/southamerica-east1/networkEndpointGroups/neg-frontend-rj
- balancingMode: UTILIZATION
  capacityScaler: 1.0
  group: https://www.googleapis.com/compute/v1/projects/mensal2/regions/us-central1/networkEndpointGroups/neg-frontend-uc
connectionDraining:
  drainingTimeoutSec: 0
description: ''
enableCDN: false
loadBalancingScheme: EXTERNAL_MANAGED
logConfig:
  enable: true
  optionalMode: EXCLUDE_ALL_OPTIONAL
  sampleRate: 1.0
name: bs-frontend
outlierDetection:
  baseEjectionTime:
    nanos: 0
    seconds: 30
  consecutiveErrors: 3
  enforcingConsecutiveErrors: 100
  interval:
    nanos: 0
    seconds: 10
  maxEjectionPercent: 50
port: 80
portName: http
protocol: HTTP
sessionAffinity: NONE
timeoutSec: 30
usedBy:
- reference: https://www.googleapis.com/compute/v1/projects/mensal2/global/urlMaps/urlmap-200status
